import type { AxiosInstance } from 'axios';
import { test, expect } from '../fixtures.ts';

// The token value is only accepted if it was generated by the `/bytes` endpoint - the same call the dashboard makes.
const newToken = async (api: AxiosInstance, accountId: string) => ({
	name: 'e2e-org-token',
	value: (await api.post('/bytes')).data.data,
	account_id: accountId,
});

const listedIds = async (api: AxiosInstance, collection: string) => {
	const response = await api.get(`/items/${collection}`);
	return response.data.data.map((item: { id: string | number }) => item.id);
};

test('org tokens can be created by admins and members only, and stay private to their creator', async ({ org, actors }) => {
	const byAdmin = await actors.admin.post('/items/gp_tokens', await newToken(actors.admin, org.account_id));
	expect(byAdmin.status).toBe(200);

	const byMember = await actors.member.post('/items/gp_tokens', await newToken(actors.member, org.account_id));
	expect(byMember.status).toBe(200);

	for (const api of [ actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		expect((await api.post('/items/gp_tokens', await newToken(api, org.account_id))).status).toBe(400);
	}

	// Tokens are personal even inside the org: everybody sees their own and nothing else.
	expect(await listedIds(actors.admin, 'gp_tokens')).toEqual([ byAdmin.data.data.id ]);
	expect(await listedIds(actors.member, 'gp_tokens')).toEqual([ byMember.data.data.id ]);
	expect(await listedIds(actors.viewer, 'gp_tokens')).toEqual([]);
	expect(await listedIds(actors.outsider, 'gp_tokens')).toEqual([]);
	expect(await listedIds(actors.otherOrgAdmin, 'gp_tokens')).toEqual([]);
	// A Directus admin is not scoped by the account at all.
	expect(await listedIds(actors.directusAdmin, 'gp_tokens')).toEqual(expect.arrayContaining([ byAdmin.data.data.id, byMember.data.data.id ]));

	// And only its creator - or a Directus admin - can edit it.
	const memberToken = `/items/gp_tokens/${byMember.data.data.id}`;

	for (const api of [ actors.member, actors.directusAdmin ]) {
		expect((await api.patch(memberToken, { name: 'e2e-renamed-token' })).status).toBe(200);
	}

	for (const api of [ actors.admin, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		expect((await api.patch(memberToken, { name: 'e2e-renamed-by-somebody-else' })).status).toBe(403);
	}
});

test('a token can not be created for the personal account of somebody else', async ({ org, user: outsider, actors }) => {
	expect((await actors.outsider.post('/items/gp_tokens', await newToken(actors.outsider, outsider.account_id))).status).toBe(200);

	// Nobody else reaches the personal account of the outsider.
	for (const api of [ actors.admin, actors.member, actors.viewer, actors.otherOrgAdmin ]) {
		expect((await api.post('/items/gp_tokens', await newToken(api, outsider.account_id))).status).toBe(400);
	}

	// And being an admin of the org the user belongs to gives no access to their personal account either.
	expect((await actors.admin.post('/items/gp_tokens', await newToken(actors.admin, org.member.account_id))).status).toBe(400);

	// A Directus admin acts on behalf of any account, including an org they are not a member of.
	expect((await actors.directusAdmin.post('/items/gp_tokens', await newToken(actors.directusAdmin, org.account_id))).status).toBe(200);
});

test('a personal token is invisible to the org and can only be deleted by its owner', async ({ org, actors }) => {
	const created = await actors.member.post('/items/gp_tokens', await newToken(actors.member, org.member.account_id));
	expect(created.status).toBe(200);

	const tokenId = created.data.data.id;
	expect(await listedIds(actors.member, 'gp_tokens')).toEqual([ tokenId ]);

	for (const api of [ actors.admin, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		expect(await listedIds(api, 'gp_tokens')).toEqual([]);
		expect((await api.delete(`/items/gp_tokens/${tokenId}`)).status).toBe(403);
	}

	expect(await listedIds(actors.directusAdmin, 'gp_tokens')).toEqual(expect.arrayContaining([ tokenId ]));
	expect((await actors.member.delete(`/items/gp_tokens/${tokenId}`)).status).toBe(204);
});

test('the applications list is scoped to the account', async ({ org, actors }) => {
	// An app is approved by an admin or a member, so only they have applications to list.
	for (const api of [ actors.admin, actors.member ]) {
		expect((await api.get(`/applications?accountId=${org.account_id}`)).status).toBe(200);
	}

	for (const api of [ actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		expect((await api.get(`/applications?accountId=${org.account_id}`)).status).toBe(400);
	}

	// A Directus admin reaches any account, and is the only one who lists them all at once.
	expect((await actors.directusAdmin.get(`/applications?accountId=${org.account_id}`)).status).toBe(200);
	expect((await actors.directusAdmin.get('/applications?accountId=all')).status).toBe(200);
	expect((await actors.admin.get('/applications?accountId=all')).status).toBe(400);
});
