import type { AxiosInstance } from 'axios';
import { test, expect } from '../fixtures.ts';
import { client as sql } from '../client.ts';
import { Org, User } from '../types.ts';

const getMembershipId = async (org: Org, user: User) => {
	const membership = await sql('gp_org_members').where({ org: org.id, user: user.id }).first('id');
	return membership.id as string;
};

const listedIds = async (api: AxiosInstance, collection: string) => {
	const response = await api.get(`/items/${collection}`);
	return response.data.data.map((item: { id: string | number }) => item.id);
};

test('only an org admin can change roles', async ({ org, actors }) => {
	const membershipId = await getMembershipId(org, org.member);

	// The self-promotion of a member is the reason the hook exists: the permission alone lets them update their own row.
	for (const api of [ actors.member, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		const response = await api.patch(`/items/gp_org_members/${membershipId}`, { role: 'admin' });
		expect(response.status).toBe(400);
		expect(response.data.errors[0].message).toBe('Only an admin of the org can change roles.');
	}

	expect((await actors.admin.patch(`/items/gp_org_members/${membershipId}`, { role: 'viewer' })).status).toBe(200);

	const membership = await sql('gp_org_members').where({ id: membershipId }).first('role');
	expect(membership.role).toBe('viewer');

	// A Directus admin manages the roles of an org they are not a member of.
	expect((await actors.directusAdmin.patch(`/items/gp_org_members/${membershipId}`, { role: 'member' })).status).toBe(200);

	const restored = await sql('gp_org_members').where({ id: membershipId }).first('role');
	expect(restored.role).toBe('member');
});

test('notification preferences can only be changed on your own membership', async ({ org, actors }) => {
	const membershipId = await getMembershipId(org, org.member);
	const preferences = { low_credits: { enabled: true, parameter: 8000 } };

	expect((await actors.member.patch(`/items/gp_org_members/${membershipId}`, { notification_preferences: preferences })).status).toBe(200);

	for (const api of [ actors.admin, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		const response = await api.patch(`/items/gp_org_members/${membershipId}`, { notification_preferences: preferences });
		expect(response.status).toBe(400);
		expect(response.data.errors[0].message).toBe('Notification preferences can only be changed on your own membership.');
	}

	expect((await actors.directusAdmin.patch(`/items/gp_org_members/${membershipId}`, { notification_preferences: preferences })).status).toBe(200);
});

test('an org is only visible to its own members, and its adoption token only to its admins', async ({ org, org2, actors }) => {
	const forAdmin = await actors.admin.get(`/items/gp_orgs/${org.id}`);
	expect(forAdmin.data.data.adoption_token).toBe(org.adoption_token);

	for (const api of [ actors.member, actors.viewer ]) {
		const response = await api.get(`/items/gp_orgs/${org.id}`);
		expect(response.data.data.name).toBe(org.name);
		expect(response.data.data.adoption_token).toBeUndefined();
	}

	for (const api of [ actors.outsider, actors.otherOrgAdmin ]) {
		expect((await api.get(`/items/gp_orgs/${org.id}`)).status).toBe(403);
	}

	const forDirectusAdmin = await actors.directusAdmin.get(`/items/gp_orgs/${org.id}`);
	expect(forDirectusAdmin.data.data.adoption_token).toBe(org.adoption_token);

	expect(await listedIds(actors.member, 'gp_orgs')).toEqual([ org.id ]);
	expect(await listedIds(actors.outsider, 'gp_orgs')).toEqual([]);
	expect(await listedIds(actors.otherOrgAdmin, 'gp_orgs')).toEqual([ org2.id ]);
	expect(await listedIds(actors.directusAdmin, 'gp_orgs')).toEqual(expect.arrayContaining([ org.id, org2.id ]));

	// The accounts themselves are not exposed to the users: they are only ever reached through the items they own.
	for (const api of [ actors.admin, actors.member, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		expect((await api.get('/items/gp_accounts')).status).toBe(403);
	}

	expect((await actors.directusAdmin.get('/items/gp_accounts')).status).toBe(200);
});

test('the org adoption token can only be regenerated by an admin, and nothing else about the org is editable', async ({ org, actors }) => {
	for (const api of [ actors.member, actors.viewer, actors.outsider, actors.otherOrgAdmin ]) {
		const token = (await api.post('/bytes')).data.data;
		expect((await api.patch(`/items/gp_orgs/${org.id}`, { adoption_token: token })).status).toBe(403);
	}

	const newAdoptionToken = (await actors.admin.post('/bytes')).data.data;
	expect((await actors.admin.patch(`/items/gp_orgs/${org.id}`, { adoption_token: newAdoptionToken })).status).toBe(200);

	// The name and the GitHub id belong to the sync, not to the admin.
	expect((await actors.admin.patch(`/items/gp_orgs/${org.id}`, { name: 'e2e-renamed-org' })).status).toBe(403);

	const stored = await sql('gp_orgs').where({ id: org.id }).first('adoption_token', 'name');
	expect(stored.adoption_token).toBe(newAdoptionToken);
	expect(stored.name).toBe(org.name);

	// A Directus admin is not limited to the adoption token, nor to the orgs they are a member of.
	expect((await actors.directusAdmin.patch(`/items/gp_orgs/${org.id}`, { name: 'e2e-renamed-org' })).status).toBe(200);
	const renamed = await sql('gp_orgs').where({ id: org.id }).first('name');
	expect(renamed.name).toBe('e2e-renamed-org');
});

// PHASE4: remove together with the `userId` parameter.
test('the legacy userId parameter is only accepted for yourself, or from a Directus admin', async ({ org, user: outsider, actors }) => {
	expect((await actors.member.get(`/credits-timeline?userId=${org.member.id}`)).status).toBe(200);
	expect((await actors.member.get(`/credits-timeline?userId=${outsider.id}`)).status).toBe(400);
	expect((await actors.member.get(`/applications?userId=${outsider.id}`)).status).toBe(400);

	expect((await actors.directusAdmin.get(`/credits-timeline?userId=${outsider.id}`)).status).toBe(200);
	expect((await actors.directusAdmin.get(`/applications?userId=${outsider.id}`)).status).toBe(200);
});
