name: E2E

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Run e2e tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install
      - name: Install Playwright browsers
        run: |
          pnpm exec playwright install --with-deps chromium
      - name: Generate env files
        run: |
          cp .env.docker.e2e.example .env.docker.e2e
          cp .env.scripts.e2e.example .env.scripts.e2e
      - name: Build docker compose
        run: |
          pnpm run test:e2e:build:directus
      - name: Build dashboard repo
        env:
            CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          pnpm run test:e2e:build:dash
      - name: Run tests
        run: |
          pnpm run test:e2e:run
